@startuml

abstract class TipoEvolucion{
    + {abstract} evolucionar(TipoEvolucion:unTipo):void
}

class Juego {
}

class Zangano{

}
class Larva{

}
class RazaZerg{

}
class Criadero{
    +removerLarva():Individuo
    +ejecutarTurno():void
}

abstract class TipoEvolucion{

}

abstract class Edificio{

}
class Extractor{

}

Individuo *-- TipoEvolucion
Zangano  -up--|> TipoEvolucion
Larva    -up--|> TipoEvolucion
RazaZerg "1"  o-- "*" Edificio
RazaZerg "1"  o-- "*" Individuo
Criadero -up--|> Edificio
Extractor -up--|> Edificio
Juego "1"  o-- "1" RazaZerg
Juego "1"  *-- "1" Mapa

@enduml

//Que al evolucionar un zanagano se cree un edificio en la misma pos
// y se elimine el zangano.