@startuml
'https://plantuml.com/class-diagram

abstract class Edificio {
    -hp: HitPoints
    #cantTurnosParaSerOperativo: Int
    -ubicacion: Ubicacion
    +ejecutarTurno():void
    + {abstract} construirEdificioEn(recurso: Recurso)
    + {abstract} verificarSiPuedeSerConstruido(unidadesDeMineral:Int, unidadesDeGas:Int)
    + {abstract} consumirGas(UnidadesDeGas:Int):Int
    + {abstract} consumirMineral(UnidadesDeMineral:Int):Int
    +recibirDaño(int daño)
    +regeneracionFinDeTurno()
    +vidaActual():Int
    +escudoActual():Int
    + {abstract} verificarCorrelativas(edificios: ArrayList)
    + {abstract} esNecesarioParaConstruirGuarida():Boolean
    + {abstract} esNecesarioParaPuertoEstelar():Boolean
    + ubicar(unLugar:Ubicacion)
    + distancia(unaUbicacion: Ubicacion): int
    +recibirAtaque(unAtaque: Ataque)
}

class Acceso{
    +transportarTropas()
    +construirEdificioEn(recurso: Recurso)
    +verificarSiPuedeSerConstruido(unidadesDeMineral:Int, unidadesDeGas:Int)
    + consumirGas(UnidadesDeGas:Int):Int
    + consumirMineral(UnidadesDeMineral:Int):Int
    + verificarCorrelativas(edificios: ArrayList)
    + esNecesarioParaConstruirGuarida():Boolean
    + esNecesarioParaPuertoEstelar():Boolean

}

class PuertoEstelar{

    +transportarUnidades()
    +construirEdificioEn(recurso: Recurso)
    +verificarSiPuedeSerConstruido(unidadesDeMineral:Int, unidadesDeGas:Int)
    + consumirGas(UnidadesDeGas:Int):Int
    + consumirMineral(UnidadesDeMineral:Int):Int
    + verificarCorrelativas(edificios: ArrayList)
    + esNecesarioParaConstruirGuarida():Boolean
    + esNecesarioParaPuertoEstelar():Boolean
}

interface Atacable {
    +recibirAtaque(ataque: Ataque)
}

Edificio <|-- Acceso
Edificio <|-- PuertoEstelar
Atacable <|.. Edificio
@enduml