@startuml
'https://plantuml.com/sequence-diagram

class Mapa{

}

class ubicación{
    Coordenada coordenada
}

class mina{
}

class geiser{
}

class limpio{
}

class moho{
}

interface estadoSuelo{
}

interface recurso{
}

estadoSuelo <|.. moho
estadoSuelo <|.. limpio
recurso <|.. geiser
recurso <|.. mina
Mapa --> "nxm" ubicación
ubicación --> estadoSuelo
ubicación --> recurso
@enduml