@startuml
'https://plantuml.com/sequence-diagram

class Mapa{
    -base:int
    -altura:int
    +buscar(unaCoordenada):unaUbicacion
    +buscar(unaCoordenada,unaDistancia):Lista(ubicaciones)
    +distanciaMaxima():int
    +buscarOpuesto(unaCoordenada):unaUbicacion
    +darTipoAlMapaInicio():void
    +agregarBasesDiagonales():void
    +getDimension():void


}

class Ubicacion{
    -unEdificio: Edificio
    -unRecurso: Recurso
    -unaUnidad: Unidad
    -unTipo: Tipo
    -unaCoordenada: Coordenada

    +Ubicacion()
    +ubicar(unEdificio):void
    +ubicar(unPilon,unMapa):void
    +desalojar(unMapa):void
    +darTipo(unTipo):void
    +distancia(unaUbicacion): unaDistancia
    +coordenada():unaCoordenada
    +crecer(unRadio,unMapa):void
    +infectar():void
    +asignarUnidad(unaUnidad):void
    +establecerEnRangoAmoSupremo():void
    +energizar():void
    +desenergizar():void
    +estaBajoElRangoDeUnAmoSupremo():void
    +energizado():boolean
    +ubicarRecurso(unRecurso):void
    +existeEdificio():boolean
    +existeRecurso():boolean
    +contieneNodoMineral():boolean

}

interface Tipo {
    #unTiposuperficie:TIPOSUPERFICIE
    +instalar(unEdificio):void
    +crecer(unaCoordenada,unMapa,unRadio):void
    +ubicar(unaUnidad):void
    +getTiposuperficie():TIPOSUPERFICIE
}

class Tierra{
     +Tierra()
     +instalar(unEdificio):void
     +crecer(unaCoordenada,unMapa,unRadio):void
     +ubicar(unaUnidad):void
}
class Moho{
     +Moho()
     +instalar(unEdificio):void
     +crecer(unaCoordenada,unMapa,unRadio):void
     +ubicar(unaUnidad):void
}
class Especial{
     +Especial()
     +instalar(unEdificio):void
     +crecer(unaCoordenada,unMapa,unRadio):void
     +ubicar(unaUnidad):void
}

Mapa -> "n" Ubicacion
Ubicacion -> Tipo
Tierra ..> Tipo
Moho ..> Tipo
Especial ..> Tipo
@enduml