@startuml
'https://plantuml.com/sequence-diagram

Jugador -> Extractor: nuevoExtractor(ubicación)
Extractor -> Jugador: unExtractor
Jugador -> Zángano: nuevoZángano
Zángano -> Jugador: unZángano

group 5 veces
    Jugador -> unCriadero: finDelTurno
    Jugador -> unCriadero: comienzaElTurno
end

Jugador -> unExtractor: asignarZángano(unZángano)
unExtractor -> Jugador: Excepción EdificioEnConstrucción

@enduml