@startuml
'https://plantuml.com/sequence-diagram

Jugador -> Criadero: nuevoCriadero
Criadero -> Jugador: unCriadero
group 4 Veces
    Jugador -> unCriadero: finDelTurno
    Jugador -> unCriadero: comienzaElTurno
end
Jugador ->Criadero: engendrarZángano()
Criadero -> Jugador: unZángano


@enduml