@startuml
'https://plantuml.com/sequence-diagram

Jugador -> Criadero: nuevoCriadero
Criadero -> Jugador: unCriadero

group 3 Veces
    Jugador -> unCriadero: finDelTurno
    Jugador -> unCriadero: comienzaElTurno
end

Jugador ->Criadero: engendrarZángano()
Criadero -> Jugador: Excepción EdificioEnConstrucción


@enduml