package edu.fiuba.algo3.Controlador;

public enum RUTAS_FXML {
    INTERFACE_JUEGO,
    MENU_CRIADERO,
    MENU_PILON,
    MENU_NODO_MINERAL_PROTOSS,
    MENU_NODO_MINERAL_ZERG,
    MENU_VOLCAN_PROTOSS,
    MENU_VOLCAN_ZERG,
    MENU_ASIMILADOR,
    MENU_EXTRACTOR,
    MENU_TIERRA_PROTOSS,
    MENU_TIERRA_ZERG,
    MENU_ACCESO,
    MENU_ATACAR_ENEMIGO,
}
