@startuml
'https://plantuml.com/sequence-diagram

Jugador -> Criadero: nuevoCriaderoOperativo
Criadero --> Jugador: unCriadero

Jugador -> "unCriadero:Criadero": engendrarZángano()
"unCriadero:Criadero" -> Jugador: unZángano

Jugador -> "unCriadero:Criadero": engendrarZángano()
"unCriadero:Criadero" -> Jugador: unZángano

Jugador -> "unCriadero:Criadero": larvasRestantes
"unCriadero:Criadero" -> Jugador: 1

Jugador -> "unCriadero:Criadero": finDelTurno

Jugador -> "unCriadero:Criadero": comienzaElTurno

Jugador -> "unCriadero:Criadero": larvasRestantes
"unCriadero:Criadero" -> Jugador: 2

Jugador -> "unCriadero:Criadero": finDelTurno

Jugador -> "unCriadero:Criadero": comienzaElTurno

Jugador -> "unCriadero:Criadero": larvasRestantes
"unCriadero:Criadero" -> Jugador: 3

@enduml