@startuml
'https://plantuml.com/sequence-diagram

":jugador" -> ":Mapa": construirEdificio(coordenadas)
":Mapa" -> ":Ubicacion": construirEdificio(coordenadas)
":Ubicacion" -> ":Tierra": darTipo()
":Tierra" -> ":Ubicacion": tierra
":Ubicacion" -> ":Ubicacion": moho null
":Ubicacion" -> ":Mapa": ConstruccionFueraDelMohoError
":Mapa" -> ":jugador": ConstruccionFueraDelMohoError


@enduml