@startuml
'https://plantuml.com/sequence-diagram
title: "Movimiento del moho en el mapa luego de 5 turnos debe aumentar el radio de  moho"
autonumber
create ":Mapa"
":jugador" -> ":Mapa": new Mapa(20,20)

":jugador" -> ":Mapa": buscar(coordenadas)
create ":Moho"
":jugador" -> ":Moho": new()
":jugador" -> ":Ubicacion": darTipo(moho)
":Ubicacion" -> ":Ubicacion": crecer(unRadio, Moho)
":Ubicacion" -> ":Tipo": crecer(coord, mapa ,unRadio)
":Tipo" -> ":Ubicacion": crecerMoho
":Ubicacion" -> ":Ubicacion": crecer moho en un radio
":Ubicacion" -> ":Mapa": mapaActualizado
":Mapa" -> ":jugador": mapaActualizado
group 2 veces
      ":jugador" -> ":Mapa": ejecutarTurno
end
":Mapa" -> ":Ubicacion": buscar(coordenadas)
":Ubicacion" -> ":Ubicacion": crecer(unRadio, Moho)
":Ubicacion" -> ":Tipo": crecer(coord, mapa ,unRadio)
":Tipo" -> ":Ubicacion": crecerMoho
":Ubicacion" -> ":Ubicacion": crecer moho en un radio
":Ubicacion" -> ":Mapa": mapaActualizado
":Mapa" -> ":jugador": mapaActualizado




@enduml