@startuml
'https://plantuml.com/sequence-diagram

autonumber
":jugador" -> ":Criadero": evolucionarLarva()
":Criadero" -> ":Criadero": evolucionarLarva()
":Criadero" -> ":Larva": evolucionarLarva()
":Larva" -> ":Zangano": evolucionarLarva()
":Zangano" -> ":Criadero": zangano
":Criadero" -> ":jugador": zangano

@enduml