@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Raza Protoss gana
"TestCase:" -> "unJuego: Juego": ejecutarTurno(): void
"unJuego: Juego" -> "juan: Jugador": esElfinDeJuego(unaRaza): void
"juan: Jugador" -> "zerg: Raza": existenUnEdificios(): void
"zerg: Raza" -> "zerg: Raza": edificios.size()

"zerg: Raza" --> "juan: Jugador": FinDelJuegoGanaronLosProtoss()
"juan: Jugador" --> "unJuego: Juego": FinDelJuegoGanaronLosProtoss()

@enduml